### ISSUE TITLE
fix kernel comparison in configure.ac

### ISSUE THREAD

**Issue by cfriedt** [anobli/gbridge#1]
A couple of issues with this:

1) typo - should say 4.9.0 instead of 4.19?
2) sort does not work correctly for n.n.n
```bash
$ echo -e "4.1\n4.2" | sort -g -t .
4.1
4.2
$ echo -e "4.10\n4.2" | sort -g -t .`
4.10
4.2
```

I would suggest converting the kernel version to an unsigned integer and using that for comparison.

**Comment by anobli** [comment]
Indeed, I made a typo about kernel version ...
About the kernel version comparison, I will reuse the from greybus makefile:
kvers_cmp=$(shell [ "$(KERNELVERSION)" = "$(1)" ] && echo 1 || printf "$(1)\n$(KERNELVERSION)" | sort -V | tail -1)
This seems to do the job correctly.

**Comment by anobli** [comment]
It tooks me a lot of time but this should be fixed now.
