### ISSUE TITLE
KERNEL_DIR automatic discovery does not work on Ubuntu

### ISSUE THREAD

**Issue by cfriedt** [anobli/gbridge#2]
Automatic discovery of the kernel (source) location fails on ubuntu

**Comment by cfriedt** [comment]
It could be that Ubuntu is the culprit, actually.

**Comment by anobli** [comment]
I should try it on ubuntu.
On my current setup, I use a kernel I have built myself.
I don't know were ubuntu install the kernel source, but I would have expected them to be at same place.

**Comment by cfriedt** [comment]
Ubuntu has a lot of Ubuntu-isms, and I think you're actually doing it the correct way, by looking at the build directory.

**Comment by cfriedt** [comment]
If gb_netlink.h were exported in linux/uapi, then it would be found, I'm sure, so maybe users will just need to rely on GBDIR for the time being.
